# Generated by Django 6.0.5 on 2026-05-11 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alimento', models.CharField(max_length=200)),
                ('calorias_100g', models.FloatField()),
                ('proteinas_100g', models.FloatField(blank=True, null=True)),
                ('carbohidratos_100g', models.FloatField(blank=True, null=True)),
                ('grasas_100g', models.FloatField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('proteina', 'Proteína'), ('vegetal', 'Vegetal'), ('carbohidrato', 'Carbohidrato'), ('fruta', 'Fruta'), ('grasa', 'Grasa'), ('otro', 'Otro')], default='otro', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('factor_correccion_precio', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubigeo_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('objetivo_salud', models.CharField(choices=[('bajar_peso', 'Bajar de peso'), ('ganar_masa', 'Ganar masa muscular'), ('mantener', 'Mantener peso')], default='mantener', max_length=20)),
                ('presupuesto_semanal_limite', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diets.distrito')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEscaneoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_path', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_comida', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena'), ('Snack', 'Snack'), ('Fuera_de_plan', 'Fuera de plan')], max_length=20)),
                ('costo_estimado_al_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calorias_registradas', models.FloatField(blank=True, null=True)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
                ('alimento_detectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diets.catalogoalimento')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calorias_totales_plan', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda_origen', models.CharField(max_length=100)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(default='kg', max_length=50)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.catalogoalimento')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.departamento')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.provincia'),
        ),
    ]
