# Generated by Django 6.0.5 on 2026-07-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alimento', models.CharField(max_length=200)),
                ('calorias_100g', models.FloatField()),
                ('proteinas_100g', models.FloatField(blank=True, null=True)),
                ('carbohidratos_100g', models.FloatField(blank=True, null=True)),
                ('grasas_100g', models.FloatField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('proteina', 'Proteína'), ('vegetal', 'Vegetal'), ('carbohidrato', 'Carbohidrato'), ('fruta', 'Fruta'), ('grasa', 'Grasa'), ('otro', 'Otro')], default='otro', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DietTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calorias_totales', models.IntegerField()),
                ('proteinas_totales', models.FloatField(blank=True, null=True)),
                ('carbohidratos_totales', models.FloatField(blank=True, null=True)),
                ('grasas_totales', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DietIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gramos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dia_de_semana', models.IntegerField(default=1, help_text='1=Lunes, 7=Domingo')),
                ('tipo_comida', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena'), ('Snack', 'Snack')], max_length=20)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.catalogoalimento')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='diets.diettemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PlanDieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calorias_totales_plan', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tienda_origen', models.CharField(max_length=100)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(default='kg', max_length=50)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diets.catalogoalimento')),
            ],
        ),
    ]
