# Generated by Django 6.0.5 on 2026-07-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diets', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEscaneoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_path', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_comida', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Almuerzo', 'Almuerzo'), ('Cena', 'Cena'), ('Snack', 'Snack'), ('Fuera_de_plan', 'Fuera de plan')], max_length=20)),
                ('cantidad_gramos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('costo_estimado_al_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calorias_registradas', models.FloatField(blank=True, null=True)),
                ('proteinas_registradas', models.FloatField(blank=True, null=True)),
                ('carbohidratos_registrados', models.FloatField(blank=True, null=True)),
                ('grasas_registradas', models.FloatField(blank=True, null=True)),
                ('fecha_escaneo', models.DateTimeField(auto_now_add=True)),
                ('alimento_detectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diets.catalogoalimento')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
            ],
        ),
    ]
