# Generated by Django 5.0.14 on 2026-07-02 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        ('users', '0002_alter_departamento_id_alter_distrito_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logescaneoia',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LogAgua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ml', models.IntegerField(default=250)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilusuario')),
            ],
        ),
    ]
